[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/agenda/2024-1/12/index.html"
to = "/agenda/2024/12/"

[[redirects]]
from = "/agenda/2024-04-11-salon-resolution/index.html"
to = "/agenda/2024/salon-resolution/"

[[redirects]]
from = "/agenda/2024-1/02/index.html"
to = "/agenda/2024/02/"

[[redirects]]
from = "/agenda/2024-1/07/index.html"
to = "/agenda/2024/07/"

[[redirects]]
from = "/agenda/2024-1/01/index.html"
to = "/agenda/2024/01/"

[[redirects]]
from = "/agenda/2024-1/08/index.html"
to = "/agenda/2024/08/"

[[redirects]]
from = "/agenda/2024-1/04/index.html"
to = "/agenda/2024/04/"

[[redirects]]
from = "/agenda/2024-1/05/index.html"
to = "/agenda/2024/05/"

[[redirects]]
from = "/agenda/2024-1/09/index.html"
to = "/agenda/2024/09/"

[[redirects]]
from = "/agenda/2024-1/11/index.html"
to = "/agenda/2024/11/"

[[redirects]]
from = "/agenda/2024-1/03/index.html"
to = "/agenda/2024/03/"

[[redirects]]
from = "/agenda/2024-1/index.html"
to = "/agenda/2024/"

[[redirects]]
from = "/agenda/2024-1/06/index.html"
to = "/agenda/2024/06/"

[[redirects]]
from = "/agenda/2024-1/10/index.html"
to = "/agenda/2024/10/"

